# Generated by Django 4.0.10 on 2023-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'Item is in stock'), ('Out of Stock', 'Item is out of stock')], default='In Stock', max_length=50)),
                ('offers', models.CharField(choices=[('No Offer', 'Currently No offer for this item'), ('10% Off', '10 percent off for this item'), ('25% Off', '25 percent off for this item'), ('Buy 1 Get 1', 'Buy one of this item and get other one free')], default='No Offer', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dairy_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'Item is in stock'), ('Out of Stock', 'Item is out of stock')], default='In Stock', max_length=50)),
                ('offers', models.CharField(choices=[('No Offer', 'Currently No offer for this item'), ('10% Off', '10 percent off for this item'), ('25% Off', '25 percent off for this item'), ('Buy 1 Get 1', 'Buy one of this item and get other one free')], default='No Offer', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'Item is in stock'), ('Out of Stock', 'Item is out of stock')], default='In Stock', max_length=50)),
                ('offers', models.CharField(choices=[('No Offer', 'Currently No offer for this item'), ('10% Off', '10 percent off for this item'), ('25% Off', '25 percent off for this item'), ('Buy 1 Get 1', 'Buy one of this item and get other one free')], default='No Offer', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'Item is in stock'), ('Out of Stock', 'Item is out of stock')], default='In Stock', max_length=50)),
                ('offers', models.CharField(choices=[('No Offer', 'Currently No offer for this item'), ('10% Off', '10 percent off for this item'), ('25% Off', '25 percent off for this item'), ('Buy 1 Get 1', 'Buy one of this item and get other one free')], default='No Offer', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'Item is in stock'), ('Out of Stock', 'Item is out of stock')], default='In Stock', max_length=50)),
                ('offers', models.CharField(choices=[('No Offer', 'Currently No offer for this item'), ('10% Off', '10 percent off for this item'), ('25% Off', '25 percent off for this item'), ('Buy 1 Get 1', 'Buy one of this item and get other one free')], default='No Offer', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
